### ISSUE TITLE
Brainfuck v2 implementations are broken

### ISSUE THREAD

**Issue by brk** [kostya/benchmarks#112]
The benchmarked implementations of brainfuck are (mostly) not correct. I tested the C and Python versions, but I suspect they all share an algorithmic bug.

Failing testcase: http://esoteric.sange.fi/brainfuck/bf-source/prog/BOTTLES.BF

Correct reference interpreter (generator): https://github.com/pablojorge/brainfuck/blob/master/haskell/bf2c.hs

Expected behavior: print bottles from 99 to zero, quickly.

Actual behavior: BF interpreters freeze after 91 bottles remain.

**Comment by kostya** [comment]
this is strange, i not see any bug in implementation.

**Comment by kostya** [comment]
i think some bug in bottles.bf file, i find another example: https://raw.githubusercontent.com/andrewtholt/4th/1574fc7e3ed1a3a4d6085fca19469c125ae3f390/4th/apps/bf/bottles.b, this works ok

**Comment by brk** [comment]
Using bf.py from the brainfuck2 directory:

```
$ python2 bf.py BOTTLES.BF
99 Bottles of beer on the wall
99 Bottles of beer
[...]
91 Bottles of beer on the wall
91 Bottles of beer
Take one down and pass it around
^C
```

Do you get different results?

The semantics of brainfuck are given on the [Wikipedia](https://en.wikipedia.org/wiki/Brainfuck) page by translation to snippets of C code. In particular, `[` and `]` corresponds to a while-loop.

[bf2c.hs](https://github.com/pablojorge/brainfuck/blob/master/haskell/bf2c.hs) does literally that: it generates snippets of C code for each character of brainfuck input.

```
$ runhaskell bf2c.hs < BOTTLES.BF > gen.c
$ gcc gen.c -o gen.exe
$ ./gen.exe
99 Bottles of beer on the wall
99 Bottles of beer
Take one down and pass it around
98 Bottles of beer on the wall
[...]
1 Bottle of beer on the wall
1 Bottle of beer
Take one down and pass it around
0 Bottles of beer on the wall

$
```

The linked BOTTLES.BF file produces different output in the two implementations. That means that either the Python interpreter has a subtle bug, or there's a bug in the translation into C code, right?
