### ISSUE TITLE
Repeat benchmarks to eliminate noise

### ISSUE THREAD

**Issue by dtolnay** [kostya/benchmarks#121]
I can run the same benchmark a few times and get wildly different results. Consider having xtime.rb loop 10-100 times and take the minimum to filter out some of this noise.

**Comment by kostya** [comment]
i run every bench some times and write best result, and not much difference, only in json example, because first time big file loaded to os cache.

**Comment by dtolnay** [comment]
Would you be open to a PR that adds this to xtime.rb? That way it is easier to compare two different versions of a binary that I am working on. I opened #122 but feel free to close if this would disrupt your workflow.
