### ISSUE TITLE
Runtime & Compiler Updates

### ISSUE THREAD

**Issue by ohenepee** [kostya/benchmarks#129]
Crystal 0.20.0 [b0cc6f7] (2016-11-22)
[latest is 0.21.0]

LDC - the LLVM D compiler (0.15.2-beta1)
[latest is 1.2.0-beta1]

DMD64 D Compiler v2.068.0
[latest is v2.073.2]

gdc (crosstool-NG crosstool-ng-1.20.0-232-gc746732 - 20150830-2.066.1-dadb5a3784) 5.2.0
[latest is 2.068.2]

**Comment by Wulfklaue** [comment]
Crystal is at 0.22.0
LDC is at 1.3.0-beta1
Rust is at 1.17

Missing: (free)Pascal?

**Comment by Wulfklaue** [comment]
Small update:

* LDC is currently at 1.4.0-beta1. 
* LDC 1.3.0 Stable has been released a while now. 
* The current benchmark version is using **LDC 0.15.2 beta1** from **March 20, 2015**, limiting to LLVM 3.0 - 3.6 Max ( unclear what LLVM version was used in the benchmark ).

* gdc is also horrible out of date. D is not officially included in GCC as a standard language.
* DMD64 D Compiler v2.068.0 was on released Aug 09, 2015. The current version is 2.076.0.

So about 2 years between the tested compilers. While Go, Crystal etc are all using much more recent compilers ( and LLVM versions in case of the languages that use LLVM ).

**Comment by kostya** [comment]
add some updates

**Comment by ohenepee** [comment]
NodeJS `9.1.0`
PHP `7.1.11`
Crystal `0.23.1`
Nim `0.17.2`
Rust `1.21`
Go `1.9.2`
D (LDC) `1.5.0`
