### ISSUE TITLE
Please update Nim, Crystal, Clang and Perl.

### ISSUE THREAD

**Issue by akzhan** [kostya/benchmarks#133]
Please update

* Nim to 0.17.0
* Crystal to 0.23.0
* Clang to 4.0.0
* Perl to 5.26.0

**Comment by Wulfklaue** [comment]
Might be also interesting to add Kotlin Native / Scala Native ...

**Comment by ohenepee** [comment]
**NodeJS** also needs an update
Current Version is `8.1.3`

**Comment by sir4ju1** [comment]
**Dotnet Core** `2.0 preview 2` is out too.

**Comment by kostya** [comment]
add some updates

**Comment by saolof** [comment]
Also, Julia. Update from 0.4 to 0.6. The number of optimizations that have been added since then is staggering.

**Comment by ohenepee** [comment]
Update **NodeJS**.... current version is `9.0.0`

**Comment by akzhan** [comment]
Crystal 0.24

**Comment by ohenepee** [comment]
Update **NodeJS**... current version is `9.4.0`

**Comment by hlaaftana** [comment]
Nim 0.18.0

**Comment by Beyarz** [comment]
Crystal 0.24 increased the precision of Time to nanoseconds.

**Comment by Doaxan** [comment]
It would be interesting to see the updated version of benchmarks

**Comment by ohenepee** [comment]
@kostya could you please update the runtimes & interpreters? Its been 8+ months since you last updated them.

**Comment by kostya** [comment]
right now i have no access to the test machine.

**Comment by diegobernardes** [comment]
Go is also outdated, 1.12 the last release.
