### ISSUE TITLE
BF benchmark: Kotlin uses arrays while Java and C# use lists.

### ISSUE THREAD

**Issue by orthoxerox** [kostya/benchmarks#135]
Hi. If you change C# to use `int[]` instead of `List<int>` for the tape and the program, it becomes much faster. Please align the implementations to use the same abstractions. If you want, I can submit a PR for C#, but I think it's better to change the Kotlin version.

**Comment by kostya** [comment]
as i know array is no resided in csharp, so i use list. can you give some pr?

**Comment by orthoxerox** [comment]
https://github.com/kostya/benchmarks/pull/136
