### ISSUE TITLE
BF2: Kotlin does not flush stdout after each character

### ISSUE THREAD

**Issue by JustANull** [kostya/benchmarks#138]
On [this line of the Kotlin program](https://github.com/kostya/benchmarks/blob/9ae0eab6e8b988d97f0762f129db6dee8e330b9c/brainfuck2/bf2.kt#L70), printing is handled. Kotlin's `.print(char)` function calls directly into Java's print function, which flushes on new line. Kotlin should flush the output stream after each character is printed to implement the behavior specified in the README, that "stdout should be flushed after each symbol."

An alternative solution would be to not flush stdout in the other languages, instead leaving it up to the standard library's natural flow.

**Comment by kostya** [comment]
i think it actually flushed, because every char appears separately.
without flush it would appears together.
