### ISSUE TITLE
Please upgrade LDC / DMD / GDC version to latest

### ISSUE THREAD

**Issue by zoujiaqing** [kostya/benchmarks#170]
LDC latest version is 1.18.0
DMD latest version is 2.088.0
GDC latest version is 9.2.0

Thanks for your work!!!

**Comment by lbmn** [comment]
DMD is now at 2.08**_5_**.

Please also upgrade Nim as well as its gcc / clang backends to latest stable versions.

The race between Nim and Dlang is most interesting!

It would also be interesting to try Nim with more backends, like [icc](https://en.wikipedia.org/wiki/Intel_C%2B%2B_Compiler), [pcc](https://en.wikipedia.org/wiki/Portable_C_Compiler), [tcc](https://en.wikipedia.org/wiki/Tiny_C_Compiler), etc.
