### ISSUE TITLE
Sad this isn't being updated anymore...

### ISSUE THREAD

**Issue by lbmn** [kostya/benchmarks#179]
This was one of the best programming language benchmarks I was able to find anywhere!  (As ye olde [Benchmarks Game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/) has made itself irrelevant by excluding top contenders like D and Nim.)  But performance competition is very dynamic, and a benchmark can only be relevant if it reflects the latest versions.  Very sad that the results haven't been updated in 200 days...

**Comment by nuald** [comment]
I'm going to help with the project in my spare time, closing this ticket as less relevant now.
