### ISSUE TITLE
Mono is faster with --llvm flag

### ISSUE THREAD

**Issue by ZelimDamian** [kostya/benchmarks#20]
Hi,

On my setup OSX 10.10 with Mono JIT compiler version 3.12.0 Mono . When I run matmult.exe with ```--llvm``` flag enabled it takes __11.71s__, whereas the original took __21.60s__.

Resulting run command looks like:
```sh
../xtime.rb mono -O=all --gc=sgen --llvm matmul.exe 1500
```
Is there such option on your Ubuntu setup? If yes, would you check how it affects the performance?

**Comment by kostya** [comment]
thanks, i`ll try it later

**Comment by kostya** [comment]
my mono says: `Mono Warning: --llvm not enabled in this runtime.`

**Comment by ZelimDamian** [comment]
That's a shame.

Do you think its fair to run perf tests with a non-default flag enabled? It is a default enabled flag on OSX though.

It seems to be relatively easy to enable the ```--llvm``` flag:
```
cd ~/src/mono
git clone https://github.com/mono/mono.git
cd mono
git checkout mono-3.2.5
export MONO_USE_LLVM=1
./autogen.sh –prefix=/opt/local –enable-llvm=yes –with-sgen=yes –with-gc=sgen
make get-monolite-latest
make EXTERNAL_MCS=${PWD}/mcs/class/lib/monolite/gmcs.exe
sudo make install
```
As seen here: http://brianreiter.org/2013/12/03/compiling-mono-3-from-source-with-llvm-code-generation-in-ubuntu-lts-x64/

**Comment by kostya** [comment]
i tried to compile it, but without luck, mono just crashed with llvm options, sorry
