### ISSUE TITLE
How do I reproduce `benchmark.b` results?

### ISSUE THREAD

**Issue by Pzixel** [kostya/benchmarks#205]
I wanted to look why rust is so slow in this benchmark: 2 sec for kotlin and almost 4 sec for Rust.

So I clone the repo run the benchs and I get following

```
pzixe@ZPC MINGW64 ~/Documents/Repos/benchmarks (master)
$ winpty docker run -it --rm -v "C:\Users\pzixe\Documents\Repos\benchmarks":/src benchmarks brainfuck2 bench
Cpp
18.43s, 3.5Mb
Rust
20.04s, 2.0Mb

pzixe@ZPC MINGW64 ~/Documents/Repos/benchmarks (master)
$ winpty docker run -it --rm -v "C:\Users\pzixe\Documents\Repos\benchmarks":/src benchmarks brainfuck2 bench
Cpp
18.50s, 3.6Mb
Rust
20.03s, 2.0Mb
```

For some reason it runs much longer than anything in the table, Both Cpp (second best result in the table) and Rust.

_(I removed other languages from benchmarking to save some time, I spent several hours to install 30 layers of initial docker file, this is why they don't appear in benchmark statistics, but it shouldn't affect anything. [See commit](https://github.com/Pzixel/benchmarks/commit/07b62dcf62b8fc2024239de5e6a759c30e9154aa) for details)_

Am I doing anything wrong?

**Comment by kostya** [comment]
Running benchmark in docker from windows not correct, vm can add unknown amount of penalty. Try native rust and c in windows.

**Comment by Pzixel** [comment]
I'd like to run C or Rust natively but unfortunately it requires running ruby script while I don't have one installed.

Any known workaround for that?

**Comment by kostya** [comment]
ruby script needs just to measure memory usage, you can just time `time ./bin_rs bench.b`

**Comment by Pzixel** [comment]
Thanks, now numbers are aligned much better

```
pzixe@ZPC MINGW64 ~/Documents/Repos/benchmarks/brainfuck2 (test_rust_cpp)
$ time ./bin_cpp.exe bench.b
ZYXWVUTSRQPONMLKJIHGFEDCBA

real    0m1.352s
user    0m0.000s
sys     0m0.015s

pzixe@ZPC MINGW64 ~/Documents/Repos/benchmarks/brainfuck2 (test_rust_cpp)
$ time ./bin_rs bench.b
ZYXWVUTSRQPONMLKJIHGFEDCBA

real    0m1.679s
user    0m0.000s
sys     0m0.015s
```

Although my results are somewhat different. In the table we had 3.43/2.41= 40% slower when my results are 1.67/1.35 = 20% slower (in average).
