### ISSUE TITLE
C#/.NET Core Json using System.Text.Json

### ISSUE THREAD

**Issue by yruson** [kostya/benchmarks#214]
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=netcore-3.0

**Comment by nuald** [comment]
Unfortunately, Mono doesn't have the internal support for System.Text.Json (yet?) I've tried to use a NuGet package for it, but it has a lot of dependencies (https://www.nuget.org/packages/System.Text.Json) including MS-specific ones. If you're willing to update the tests to use System.Text.Json for both Mono and .NET CLI, please send a corresponding PR.

I guess we can diverge the codebases and use System.Text.Json for .NET Core and something more appropriate for Mono, but I'm not sure what's the standard (built-in?) way to parse JSON in Mono nowadays.

**Comment by yruson** [comment]
Sorry I have n’t used Mono, but System.Text.Json is already the built-in standard library of .net core3.0 and it is also officially recommended

**Comment by yruson** [comment]
System.Text.Json.JsonSerializer.Serialize<T>(T value)
System.Text.Json.JsonSerializer.Deserialize<T>(string json)

**Comment by nuald** [comment]
The new test has been added for this use-case. Unfortunately, the current implementation of System.Text.Json doesn't perform better than the Newtonsoft.Json, so I left the old code as-is.
