### ISSUE TITLE
Anyone know Swift Open Silver/Elements benchmark?

### ISSUE THREAD

**Issue by nob-suz** [kostya/benchmarks#24]
Open Swift project Elements/Silver become alfa.
http://elementscompiler.com/elements/silver/
It might  developed by Delfi/ObjectivePascal

**Comment by kostya** [comment]
not understand what you want to say

**Comment by nob-suz** [comment]
Hi, thanks for many benchmark information.
I am interested in comparing Swift and Crystal,so I also try benchmark data if I have time to.
I want more information about Swift open compiler,
if not the place I will close soon.

**Comment by asterite** [comment]
@nob-suz is Swift open source?

**Comment by nob-suz** [comment]
Hi, this Elements/Silver is  not open source,but free trial .
http://elementscompiler.com/elements/silver/
I heard Phoenix Swift open source project ever,but might not go in progres
https://source.ind.ie/project/phoenix/tree/master/phoenix.xcodeproj
