### ISSUE TITLE
ServerGarbageCollection for .NET Core

### ISSUE THREAD

**Issue by igouy** [kostya/benchmarks#251]
When I re-ran a few of the Havlak programs on my old computer, the most noticeable elapsed-time difference was .NET Core C# program was faster than the Go program — contrary to what you show.

I can make the C# program slower than the Go program by not using [ServerGarbageCollection](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#systemgcservercomplus_gcserver).

My guess is you're running the default Workstation GC?

Whether you decide that's the right or wrong thing to do, it would be good to mention on the results page.

**Comment by nuald** [comment]
That's a good point - server GC has been enabled and the preliminary results are similar to yours. The actual results will be published during the next scheduled update.
