### ISSUE TITLE
ConcurrentGarbageCollection for .NET Core

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [kostya/benchmarks#255]
Similar to #251, I noticed that the (questionable) Computer Language Benchmarks Game enables _both_ ServerGarbageCollection and ConcurrentGarbageCollection, as shown at https://benchmarksgame-team.pages.debian.net/benchmarksgame/measurements/csharpcore.html

I don't use any .NET languages, but any standard optimizations should be used for all represented languages.

**Comment by nuald** [comment]
ConcurrentGarbageCollection is enabled by default (https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector), but I've set it explicitly in the new upcoming major update.

**Comment by OpenSourceAnarchist** [comment]
I wasn't sure if setting ServerGarbageCollection to true would set ConcurrentGarbageCollection to false since Microsoft recommends concurrent gc for workstations, not for servers. Regardless, thanks for making it explicit and I look forward to the new update!

**Comment by nuald** [comment]
Addressed in #257.
