### ISSUE TITLE
Intel JCC bug 

### ISSUE THREAD

**Issue by beached** [kostya/benchmarks#263]
gcc supports a work around for the Intel JCC bug, but it is opt in via `-Wa,-mbranches-within-32B-boundaries` command line option.  There is a performance regression in most modern Intel chips when conditionals overlap or end on 32bit boundaries.

Background: https://www.intel.com/content/dam/support/us/en/documents/processors/mitigations-jump-conditional-code-erratum.pdf

**Comment by nuald** [comment]
Fixed for GCC. Apparently, Clang has the similar option, but it's not available in the stable version yet.

**Comment by beached** [comment]
It should be in clang 10, `-mbranches-within-32B-boundaries` is the option.

**Comment by nuald** [comment]
Thanks, I couldn't find this option in their docs. Updated the flags, and provided new results (it's only one test now).
