### ISSUE TITLE
Update names

### ISSUE THREAD

**Issue by RUSshy** [kostya/benchmarks#269]
Hi

Currently hard to see D lang, you have used compiler names..

Would be:

LDC -> D LDC
DMD -> D DMD
GCD -> D GCD

Better,

instead of NAME + COMPILER

Let's do this: 

D (LDC)

Same for GO:

Instead of:  GCC Go, it becomes: Go (GCC)

Better for clarity and avoid confusions

**Comment by nuald** [comment]
I agree that naming could be better, however I'd like to note that we need to specify more than just language + compiler here, but additional information too, e.g.:
 - framework (C# Mono vs C# .NET Core)
 - used libraries (Haskell vs Haskell MArray)
 - used options (Ruby vs Ruby JIT)
 - used approach in the test (Tcl FP vs Tcl OO)

My suggestion would be to use multi-part name with the structure like: language/[compiler|framework] ([options|libraries|approach])

In that case, the aforementioned examples would look like:
- C#/Mono vs C#/.NET Core
- Haskell vs Haskell (MArray)
- Ruby vs Ruby (--jit)
- Tcl (FP) vs Tcl (OOP)

What do you think, @RUSshy ?

**Comment by RUSshy** [comment]
That would help a lot when analyzing the results!

One other crazy and more long term suggestion is to do something like: 

https://www.techempower.com/benchmarks/

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks

**Comment by nuald** [comment]
I'll change names, but as it requires source code change, it'll take some time.

As for the long term, I don't think that fits the project - it's a sandbox with the average and not fine tuned code (techempower benchmarks are highly optimized).

**Comment by nuald** [comment]
@RUSshy Please take a look into PR #270 (I can't add you to the reviewers list, but would like to have a feedback).

**Comment by RUSshy** [comment]
Yes it is much more readable now
