### ISSUE TITLE
Name of json benchmark "C++/g++ (Boost)" is misleading.

### ISSUE THREAD

**Issue by ilyapopov** [kostya/benchmarks#276]
The code uses [Boost.PropertyTree](https://www.boost.org/doc/libs/1_74_0/doc/html/property_tree.html) library, which is not intended as a general purpose json parsing library. It also does not attempt to be fast at parsing JSON at all. 
I suggest it is renamed to "C++/g++ (Boost.PropertyTree)"

As the name is now, it may make people believe it is using the newer [Boost.JSON](https://github.com/boostorg/json) library, which has been just accepted to Boost and will be included in one of the next releases.

**Comment by nuald** [comment]
Addressed in #277. Added Boost.JSON test too (using Boost git HEAD for now until they have a new release).
