### ISSUE TITLE
lots of stdout logging in timing areas of code

### ISSUE THREAD

**Issue by tommyk** [kostya/benchmarks#278]
this is more of a question / comment than an actual issue.  i was poking around in some of the tests and noticed they seem to have stdout logging inside the performance measuring sections.  so it seems like these tests are kind of measuring how fast you can base64 and how fast you can slice up strings to put to stdout.

is this on purpose?  for instance, i would not pepper hot code i am trying to optimize with `Console.WriteLine` or `console.log` calls as i know that would pull performance, but it appears to be how things are tested from what i could see poking around.

thoughts?  (also, this is very cool project, thanks for making!!)

**Comment by nuald** [comment]
There are definitely concerns regarding that, and the tests should be up-to-dated to not use slicing and outputs as it affects the results. However, the effect is quite minimal as the used strings are small and those operations take milliseconds (and they're not in the loops). Nevertheless, it's better to remove those, and I hope that eventually we'll do it.

**Comment by nuald** [comment]
All outputs are moved out of the benchmarked code.
