### ISSUE TITLE
Wrong V version

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [kostya/benchmarks#345]
It looks like (at least one) of the language versions in the README don't match the actually used versions. For example, V is listed as 0.2.2 but weekly.2021.26 is listed in the docker file.

I'm not sure if there are other languages with discrepancies :)

**Comment by nuald** [comment]
That's a version reported by `v version`. Unfortunately, looks like V lang doesn't have a steady (and/or stable) release cycle yet, so I'm using weekly builds from https://github.com/vlang/v/releases I guess that as soon as they introduce proper releases, I'll switch to use them, and the discrepancy will be gone. The only change I could implement for now is including git commit hash, i.e. `0.2.2 0ac0ab6`.

**Comment by OpenSourceAnarchist** [comment]
I see, thanks for explaining. I figured `v version` would report the weekly version number. Having a commit hash would make it easier to find the exact release used, which would resolve the issue until `v` gets past their 1.0 release and hopefully reports the version correctly.

**Comment by nuald** [comment]
Addressed in #346
