### ISSUE TITLE
Mandelbrot implementation

### ISSUE THREAD

**Issue by kbrock** [kostya/benchmarks#35]
I think I missed where the Mandelbrot is implemented.

Could you link it into the readme file?

Also, very cool that you reference your source for the origin of many of these benchmarks.
Thanks

**Comment by kostya** [comment]
mandel.b is a brainfuck example with https://github.com/kostya/benchmarks/blob/master/brainfuck/mandel.b

**Comment by kbrock** [comment]
sweet - thanks
