### ISSUE TITLE
Julia native result reported for Matmul is not from xtime

### ISSUE THREAD

**Issue by John-Steidley** [kostya/benchmarks#39]
...or at least, I strongly believe it is.

I think you used its own self-reported time rather than the output of xtime.rb by mistake in this case. matmul-native.jl prints the time that it thinks it takes. This isn't fair to the other benchmarks because only the julia-native code gets to ignore the overhead of the testing framework.

On my machine I get similar results for Rust and C but Julia-native's time is way off. Instead of something close to 0.15s I get 0.75s ~5x slower than reported. On the other hand, the other languages are slightly faster, which makes sense since I'm using a new i7 instead of an i5.

**Comment by kostya** [comment]
julia vm have time to warm up, so this is fair. for other languages warm up is milliseconds.
