### ISSUE TITLE
Changing Java version

### ISSUE THREAD

**Issue by PetrovskyM** [kostya/benchmarks#405]
Hello, I am trying to change JDK version and I've had some issues. I understand that I have to start installation in Dockerfile. So I tried this:
 `ARG JDK=18
RUN wget --progress=dot:giga -O - \
    https://download.java.net/java/GA/jdk18/43f95e8614114aeaa8e8a5fcf20a682d/36/GPL/openjdk-18_linux-aarch64_bin.tar.gz \
    | tar -xz
ENV PATH="/opt/jdk-$JDK/bin:${PATH}"`

JDK downloads without any error, but when I try to run for example versions command I get following errors.

Fetching Clojure version... 
/usr/local/bin/clojure: line 426: /opt/jdk-18/bin/java: cannot execute binary file: Exec format error 
Fetching Java version... 
/opt/jdk-18/bin/java: 2: Syntax error: Unterminated quoted string 
Fetching Kotlin version... 
/opt/kotlinc/bin//kotlinc: line 98: /opt/jdk-18/bin/java: cannot execute binary file: Exec format error 
Fetching Ruby/jruby version... 
/usr/bin/jruby: line 515: /opt/jdk-18/bin/java: cannot execute binary file: Exec format error 
/usr/bin/jruby: line 515: /opt/jdk-18/bin/java: Success 

I am trying to run benchmarks with other Java versions for a school project and I would apriciate any help or 
advice. Thank you.

**Comment by nuald** [comment]
I'll push the maintenance update with the newer Java version soon, no worries.

**Comment by kostya** [comment]
Probably you download wrong version, it should not be aarch64

**Comment by nuald** [comment]
The update with the newer version has been submitted as #406. And @kostya is right, you've used AArch64 binary, but the base image is amd64, so it's expected that all binaries are for the same platform.
