### ISSUE TITLE
Docker image cannot be built out of the box

### ISSUE THREAD

**Issue by hungrybluedev** [kostya/benchmarks#417]
When I cloned the repository and tried running the first docker command to build the project, the run failed with complaints about missing packages.

I was stumped for about an hour. Finally, I used the `./run.sh update_apt` command in the last section of the README to modify `docker/apt.pkgs` and retried to build the image. This time, it works.

I think the `update_apt` command should be run periodically to keep the repo up to date, or this section should be before the `docker build` command.

**Comment by nuald** [comment]
Thanks, added the note into README.md in #419
