### ISSUE TITLE
C# benchmark with coreclr

### ISSUE THREAD

**Issue by pjmagee** [kostya/benchmarks#45]
I know we have the benchmarks with Mono but since coreclr was just released it would be great to get the benchmarks updated with that.

**Comment by kostya** [comment]
what is coercer and how install/run it on ubuntu?

**Comment by pjmagee** [comment]
Hey Kostya, [here is the guide to get coreclr running with dnx.](http://dotnet.github.io/core/getting-started/)

**Comment by pjmagee** [comment]
Apparantly, there is an overhead bug using DNX with CoreCLR to run the application. I was told to avoid the DNX overhead for the CoreCLR that the raw CoreCLR should be used.

[Build CoreCLR on Linux](https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md)

**Comment by kostya** [comment]
thats not easy, build.sh in last link just crashed with:
```
  /usr/bin/clang++-3.5 -Wall -Wno-null-conversion -std=c++11
  CMakeFiles/cmTryCompileExec2525522987.dir/testCXXCompiler.cxx.o -o
  cmTryCompileExec2525522987 -rdynamic

  /usr/bin/ld: cannot find -lstdc++

  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)

```
libstdc++-dev, libstdc++ installed

**Comment by pjmagee** [comment]
I'm not sure how to fix because I'm a Windows user. There are some issues noted on their Github with potential issues with different versions of CMake. :cry:

**Comment by shahid-pk** [comment]
Looks like you are missing some dependencies , follow this guide https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md 

Or if you don't want to compile it you can take the binaries for the coreclr's repo artifacts 
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_release/

**Comment by pjmagee** [comment]
@kostya , maybe it's better to just use the binary so you don't need to compile it, then you compile brainfuck.cs and pass the nuget libs in the compiler argument and then there is no need for project.json.

**Comment by kostya** [comment]
downloaded corerun, what next? how to compile, run?

**Comment by pjmagee** [comment]
At the moment, the Roslyn C# Compiler is not available. So to compile, you still need to use `mcs`.

[How to Compile App](https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md#compile-an-app)
[How to Run app](https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md#run-your-app)

**Comment by pjmagee** [comment]
There have been some major changes since first submitting this issue for your benchmarks. There are guides to install and run CoreCLR applications and version 1.0 has been released, as well as the editor for C# Applications on Linux using VS Code. Maybe now might be a better time to implement benchmarks for CoreCLR and .NET Core 1.0 

http://dotnet.github.io/getting-started/

**Comment by kostya** [comment]
still problems with installing :)
in step 2: 
`sudo apt-get install dotnet`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package dotnet is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'dotnet' has no installation candidate
```

```
aptitude search dotnet
p   dotnet-dev                                                                                                - .NET Core & command line tools                                                                                     
p   dotnet-nightly                                                                                            - Unstable Developer Build of .NET Core & command line tools  
```

`sudo apt-get install dotnet-dev`

in step 4:
`dotnet run`

```
Could not resolve coreclr path
```

**Comment by kostya** [comment]
may be you have docker image with installed dotnet?

**Comment by kostya** [comment]
i'll try with docker

**Comment by benaadams** [comment]
Might have been updated? Says on https://dotnet.github.io/getting-started/
```
sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'

sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

sudo apt-get update

sudo apt-get install dotnet=1.0.0.001331-1
```
