### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid() in /root/benchmarks/base64/test.php:34

### ISSUE THREAD

**Issue by martin-braun** [kostya/benchmarks#451]
The PHP base64 test fails on a musl clib system with BusyBox, such as Alpine Linux. The error is: 

> PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid() in /root/benchmarks/base64/test.php:34

PHP JSON test is affected as well. What can I do?

**Comment by nuald** [comment]
Fixed in #455
