### ISSUE TITLE
JSON PHP test fails

### ISSUE THREAD

**Issue by martin-braun** [kostya/benchmarks#452]
This fails on Debian and Alpine Linux:

`php test.php`: 

> PHP Warning:  file_get_contents(/tmp/1.json): Failed to open stream: No such file or directory in /root/benchmarks/json/test.php on line 53
> PHP Warning:  Trying to access array offset on value of type null in /root/benchmarks/json/test.php on line 24
> PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /root/benchmarks/json/test.php:25
> Stack trace:
> #0 /root/benchmarks/json/test.php(58): calc()
> #1 {main}
>   thrown in /root/benchmarks/json/test.php on line 25

`node test.php`:

> Error: ENOENT: no such file or directory, open '/tmp/1.json'
>     at Object.openSync (node:fs:600:3)
>     at Object.readFileSync (node:fs:468:35)
>     at /root/benchmarks/json/test.js:50:21
>     at Object.<anonymous> (/root/benchmarks/json/test.js:57:3)
>     at Module._compile (node:internal/modules/cjs/loader:1254:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
>     at Module.load (node:internal/modules/cjs/loader:1117:32)
>     at Module._load (node:internal/modules/cjs/loader:958:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:23:47 {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: '/tmp/1.json'
> }

Why not using `mktemp`?

**Comment by nuald** [comment]
The JSON tests require the large (100+ Mb) JSON file  created first, `mktemp` has nothing to do with it. If you don't want to use Docker environment, the file is created by running `ruby generate_json.rb` in `json` directory.

Another approach is using `make` directly. For example, to run `test.php`, one could use `make run[test.php]` in `json` directory and it will create the test JSON file automatically.

**Comment by martin-braun** [comment]
@nuald This makes sense, I will generate the JSON using Ruby. Thanks a lot!
