### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by ricvelozo** [kostya/benchmarks#457]
I want to use assertions in `verify()` functions to simplify the code. Does the error output need to be exact? Example:

```rust
if left != right {
    eprintln!("{left} != {right}");
    process::exit(-1);
}
````

Will become just:

```rust
assert_eq!(left, right);
````

The error output:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `80`,
 right: `82`', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ricvelozo** [comment]
And the `verify()` function needs to be called at runtime? Because in Swift we must disable the `-Ounchecked` flag to the assertion don't be optimized away.

**Comment by nuald** [comment]
The code is not tested in debug mode at all, so whatever verification is used, should work in the release mode too.

**Comment by ricvelozo** [comment]
> The code is not tested in debug mode at all, so whatever verification is used, should work in the release mode too.

Alright, I will use `fatalError()` in Swift (not optimized away). But the `-Ounchecked` flag is another one to go to the #290 discussion.
