### ISSUE TITLE
Reorganize and improve go code

### ISSUE THREAD

**Issue by WillAbides** [kostya/benchmarks#478]
When working on #476 I noticed that Go benchmarks are a tough to work on because they are all in the same directory so editors interpret that as one big package with a lot of duplicate function names.

I propose changing the layout of the Go benchmarks to be more like the Rust layout. There would be a `common/go` package with a `Run` function that runs the benchmarked function and sends the results to `:9001`.

Each test directory would have a `test-go` subdirectory that contains a separate package for each Go benchmark. For example there would be `json/json-go/goccy` and `json/json-go/jsoniter`.

If this gets a 👍 I can do the work. I did a little bit of exploratory work with a few json benchmarks, and it won't take too long to apply that to the rest of the Go benchmarks.

**Comment by nuald** [comment]
It's totally fine to reorganize the source code, especially considering how Go modules work. I guess after that we could finally drop `GO111MODULE=auto`, and please feel free to do that within you changes if you want.

Thanks for contributing!
