### ISSUE TITLE
Update Python results

### ISSUE THREAD

**Issue by notsatvrn** [kostya/benchmarks#494]
Would be interesting to see how a Python 3.13 build with JIT enabled and GIL disabled would perform in these tests.

**Comment by nuald** [comment]
It's not as simple as just "update Python results" as JIT is not enabled by default, and it requires to build Python from sources with the corresponding flags.

Moreover, I don't have good news here. I've manually built Python with `--disable-gil --enable-experimental-jit --enable-optimizations` (https://realpython.com/python313-free-threading-jit/), and its results are worse than the current 3.12 in the container:
```
# python3
Python 3.12.6 (main, Sep  7 2024, 14:20:15) [GCC 14.2.0] on linux

# ../xtime.rb python3 bf3.py bench.b
"CPython"
ZYXWVUTSRQPONMLKJIHGFEDCBA
55.645 s, 11 Mb, 2481.9 J

# ../cpython/python
Python 3.14.0a1+ experimental free-threading build (heads/main:47cbf03, Nov 14 2024, 20:56:36) [GCC 14.2.0] on linux

# ../xtime.rb ../cpython/python bf3.py bench.b
"CPython"
ZYXWVUTSRQPONMLKJIHGFEDCBA
154.474 s, 13 Mb, 6636.2 J

```

While it could work better in some particular use-cases, I don't see a point to include it right now, and would prefer to rather wait until they release Python with the fully functional mature JIT.

**Comment by notsatvrn** [comment]
Interesting, saw very different results in some other workloads a friend showed me. I think it makes sense to just wait until the JIT fully matures. I'll go ahead and close this issue.
