### ISSUE TITLE
Node.js UPDATE

### ISSUE THREAD

**Issue by ohenepee** [kostya/benchmarks#56]
Please kindly update the Node.js version, or at least add a new entry that goes like 'JavaScript Node Latest'.

Almost all the other languages and implementations are using bleeding edge versions except JavaScript Node.js and JavaScript V8

Node.js latest stable = 5.0.0

**Comment by kostya** [comment]
wow, it much faster

**Comment by ohenepee** [comment]
:D You're the man... Now that's what we call PERFORMANCE IMPROVEMENT
