### ISSUE TITLE
Include Vert.x JavaScript

### ISSUE THREAD

**Issue by ohenepee** [kostya/benchmarks#71]
Please include Vert.x ( http://vertx.io/ ) in your benchmarks as the polygot platform seems very promising and tends to benefit from the Java HotSpot's runtime optimizations.... perhaps some benchmark warm up will be needed. Thanks

**Comment by kostya** [comment]
i tried but noone example running, `Cannot find module fs in <eval> at line number 141`, and other errors.

**Comment by ohenepee** [comment]
Good to know... thanks
