### ISSUE TITLE
Julia Timing

### ISSUE THREAD

**Issue by ylluminate** [kostya/benchmarks#78]
One thing that I discovered in Julia is that the current benchmark is not very accurate.  It would be better to call `@time main()` in order to get the time and memory consumption sans the JIT for more accurate results.  I have found this makes some difference in the results.  For example, with `brainfuck` the results show Julia to be only 0.45 seconds slower than Crystal.

**Comment by hayd** [comment]
Other benchmarks do include start time (but not compile time), so maybe precompiling is the thing to do.

As mentioned in your [julia issue](https://github.com/JuliaLang/julia/issues/14808#issuecomment-175296406) there are bigger problems:

> check out the difference in [this implementation](https://github.com/kostya/benchmarks/blob/4441efe9b45e78c120b8741205a4c68dc647a07e/matmul/matmul.jl#L14-L21) vs [this one](https://github.com/kostya/benchmarks/blob/4441efe9b45e78c120b8741205a4c68dc647a07e/matmul/matmul.c#L31-L51). Comparing those two has nothing to do with the language, and all about comparing a good implementation against a bad one.
