### ISSUE TITLE
What about PHP?

### ISSUE THREAD

**Issue by rap2hpoutre** [kostya/benchmarks#85]
PHP is slow, we all know that, but it can be interesting to know how (should be done with PHP7 CLI I think)

EDIT: I could submit a PR if you want.

**Comment by kostya** [comment]
send a PR

**Comment by idchlife** [comment]
@rap2hpoutre what about PR? :D

**Comment by rap2hpoutre** [comment]
Oops I totally forgot. Here is a first step: https://github.com/kostya/benchmarks/pull/98

**Comment by rap2hpoutre** [comment]
@kostya Thanks for all. I think the test should be done with PHP 7 (current default version for ubuntu)

**Comment by kostya** [comment]
update to 7

**Comment by BenGermany** [comment]
Sorry, such benchmarks are very interesting, but comparing php stand-alone or behind is wasting time like sitting on a chunk of butter. It's better to use the time for updates of the really interesting languages, like Crystal, Go, Rust, Nim,...

So for php itself this would be nothing more than killing it simply - like butter in a furnace.
