### ISSUE TITLE
Julia code runs in global scope

### ISSUE THREAD

**Issue by dextorious** [kostya/benchmarks#9]
In Julia running code outside of predefined functions carries a heavy performance penalty. For instance, simply rewriting the matrix multiplication benchmark as follows yields a performance improvement by a factor of 3 on my machine:

function matgen(n)
	tmp = 1.0 / n / n
	[ float32(tmp * (i - j) * (i + j - 2)) for i=1:n, j=1:n ]
end

function main()
	n = 100
	if length(ARGS) >= 1
  		n = int(ARGS[1])
	end
	t = time()
	n = int(n / 2 * 2)
	a = matgen(n)
	b = matgen(n)
	c = a * b
	v = int(n/2) + 1
	println(c[v, v])
	println(time() - t)
end

main()
main()

The same goes for the other benchmarks. Technically, comprehensions are fairly slow too (compared to unrolled @simd/@inbounds annotated for loops), but the matrix generation doesn't particularly matter in this benchmark. Also note that the main() function is invoked twice here to show the kind of performance improvement the JIT produces (roughly 300 times on my machine). In general, it is good practice in Julia to first run performance sensitive functions on a tiny dataset to invoke the JIT, then run the actual computation.

P.S. Also note that this particular benchmark implementation essentially measures the performance of whatever OpenBLAS version you compiled Julia to use and virtually any language should be able to obtain similar results.

**Comment by asterite** [comment]
@dextorious Why can't Julia put all that code into an implicit main function? Or, put another way: why putting everything in a function makes things faster?

**Comment by dextorious** [comment]
It has to do with the scoping rules Julia currently employs. Anything outside of a function is considered to be in global scope and due to possible type stability (and other) issues global variables may face, the JIT has considerably more restrictions when operating in global scope rather than in some local function. Some of these restrictions can be circumvented by declaring constant global variables (say, const i = 1), but not all. 

As to the design choices underlying these restrictions, there are frequent discussions on this topic in the julia-users and julia-dev mailing lists, but I would not presume to speak for the developers of the language.

**Comment by kostya** [comment]
not seeing any big speedup

**Comment by tkelman** [comment]
The Julia code is still written as if it's Python, no wonder it's running slowly. Julia types should not have function members, that's an OO anti-pattern.

**Comment by kostya** [comment]
yes, i am bad at julia, pr please how to better code in it.
